---
- name: Run Ceph commands before post-deployment configuration
  hosts: mons
  gather_facts: false
  become: true
  tags:
    - cephadm
    - cephadm-commands
  tasks:
    - name: Apply commands role for pre-configuration commands
      ansible.builtin.import_role:
        name: stackhpc.cephadm.commands
      vars:
        cephadm_commands: "{{ cephadm_commands_pre | default([]) }}"
